/*#######################################################
 *
 * SPDX-FileCopyrightText: 2026 Milos Vasic
 * SPDX-License-Identifier: Apache-2.0
 *
 * Yole iOS App entry point — SwiftUI + Compose Multiplatform
 *
 * iter-78: Xcode installed + KMP shared.framework built.
 * `import shared` is now active. The ComposeView hosts the real
 * KMP/Compose UI via MainViewControllerKt.MainViewController().
 *
 * HONEST DISCLOSURE (CONST-039 / iter-78):
 * The iOS UI is the branded splash screen (YoleIosRoot) defined in
 * shared/src/iosMain/kotlin/digital/vasic/yole/MainViewController.kt.
 * Full Compose UI parity with Android/Desktop is deferred to v2.0.0.
 * Tracker: #iter-78-ios-ui-feature-parity-pending
 *
 * Cross-platform impact:
 * - Android:  N/A (uses androidMain entry)
 * - Desktop:  N/A (uses desktopMain entry)
 * - iOS:      This file — active
 * - Web:      N/A (uses wasmJsMain entry)
 *
 *########################################################*/

import SwiftUI
import UIKit
import shared

/// iOS app entry point. Uses SwiftUI @main to bootstrap the app.
/// Hosts the Compose Multiplatform UI via ComposeView.
@main
struct iOSApp: App {
    var body: some Scene {
        WindowGroup {
            ComposeView()
                // Prevent keyboard from resizing the Compose surface —
                // Compose handles insets internally via WindowInsets.
                .ignoresSafeArea(.keyboard)
        }
    }
}

/// Bridges SwiftUI to Compose Multiplatform via UIViewControllerRepresentable.
/// Hosts the KMP shared module's MainViewController (produced by Kotlin/Native).
struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        // MainViewControllerKt is generated by KMP from MainViewController.kt.
        // It returns a ComposeUIViewController hosting YoleIosRoot.
        return MainViewControllerKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}
