/*#######################################################
 *
 * SPDX-FileCopyrightText: 2026 Milos Vasic
 * SPDX-License-Identifier: Apache-2.0
 *
 * iter-57 Phase 10: post-processes ParsedDocument.toHtml() output
 * to replace fenced code-block bodies with token-CSS-classed spans.
 * Consumes SyntaxHighlighter; the active theme drives the CSS
 * (generated by `StyleSheets.tokenColorCss(theme)`).
 *
 * Discovered HTML-output conventions for fenced code blocks
 * across the Yole format parsers (inventoried 2026-05-14):
 *
 *   - PlaintextParser  → <pre><code class='language-X'>…</code></pre>
 *     (single-quoted attribute, e.g. `class='language-kotlin'`).
 *   - JsonParser       → <pre><code class='language-json'>…</code></pre>
 *     (same single-quote form).
 *   - MarkdownParser   → <pre><code>…</code></pre> (no lang class today;
 *     phase 10 augments MarkdownParser.kt to emit `class="language-X"`
 *     when a fenced block declares a language, e.g. ```kotlin).
 *   - AsciidocParser   → <pre><code>…</code></pre> (Asciidoc fenced
 *     blocks `----`/`....` do not carry an explicit language attribute;
 *     they pass through unchanged — graceful no-op).
 *   - RMarkdownParser  → emits its own <div class="code-chunk …"> wrapper;
 *     not a fenced <pre><code class="language-…"> block, so the
 *     post-processor leaves it alone.
 *
 * Accommodated class spellings (regex group 1):
 *
 *   - class="language-X"       (HTML5 standard, double quotes)
 *   - class='language-X'       (HTML5 standard, single quotes)
 *   - class="lang-X"           (some highlight.js-style emitters)
 *   - class="highlight X"      (Pygments-style)
 *
 * Anything else (no class, blank lang, unknown lang, gated-off format,
 * tokenize exception) → the original <pre><code>…</code></pre> is
 * preserved verbatim. Per spec §4 and CONST-035 we NEVER fabricate
 * token spans on a tokenize failure.
 *
 *########################################################*/
package digital.vasic.yole.syntax.render

import digital.vasic.yole.language.special.MarkdownCodeFences
import digital.vasic.yole.syntax.EnabledFormatGate
import digital.vasic.yole.syntax.SyntaxHighlighter
import digital.vasic.yole.syntax.Token
import digital.vasic.yole.syntax.TokenizerEngine
import digital.vasic.yole.syntax.grammar.ScopeMapper

/**
 * Post-process HTML produced by `ParsedDocument.toHtml()` to add
 * syntax-highlighting spans inside fenced code blocks.
 *
 * The active theme's per-scope colors are emitted as `.tok-<scope>`
 * CSS classes by `StyleSheets.tokenColorCss(theme)`; this object only
 * inserts the `<span class="tok-…">` wrappers around tokenized
 * sub-strings of each fenced code block's body.
 */
object PreviewCodeBlockHighlighter {
    /**
     * Regex matching one fenced code block in an HTML preview.
     *
     * Group 1: the language identifier (e.g. `kotlin`) extracted from
     *   the `class="language-X"`, `class='language-X'`, `class="lang-X"`,
     *   or `class="highlight X"` attribute. May be empty/absent when the
     *   `<code>` tag has no class — in that case the block is preserved
     *   verbatim (per spec §4 graceful-degradation rule: never invent a
     *   default grammar for an unlabeled block).
     * Group 2: the raw body between `<code …>` and `</code>` (HTML-escaped
     *   text as the format parser emitted it).
     *
     * The character class `[a-z0-9_+-]+` accepts grammar IDs like
     * `kotlin`, `c++`, `objective-c`, `bash`, `shell-script`, `rust`,
     * `cpp17`, etc. Case-insensitive matching is enabled so emitter
     * inconsistencies don't bite us.
     */
    private val codeBlockRegex = Regex(
        """<pre><code(?:\s[^>]*?\bclass=["'](?:language-|lang-|highlight\s+)([a-z0-9_+\-]+)["'][^>]*?)?[^>]*?>([\s\S]*?)</code></pre>""",
        RegexOption.IGNORE_CASE,
    )

    /**
     * Rewrite [html], replacing each fenced code block's body with
     * token-CSS-classed `<span>`s when the block declares a language
     * that is currently enabled in [EnabledFormatGate] and that the
     * [highlighter] can tokenize.
     *
     * Blocks left UNCHANGED:
     *  - `<code>` has no language class.
     *  - language is gated off (`EnabledFormatGate.isEnabled` returns false).
     *  - `highlighter.tokens(…)` returns an empty list.
     *  - `highlighter.tokens(…)` throws any [Throwable] (engine load
     *    failure, grammar not found, etc.).
     *
     * Surrounding HTML (paragraphs, headings, lists, tables, anything
     * outside `<pre><code>…</code></pre>` matches) is byte-identical to
     * the input.
     *
     * CONST-035 anti-bluff guarantee: on any failure path the original
     * block bytes are preserved — we never emit fake spans labeled as if
     * they were real grammar output.
     */
    suspend fun rewrite(html: String, highlighter: SyntaxHighlighter): String =
        rewrite(html, highlighter, markdownEngine = null, markdownSubEngines = emptyMap())

    /**
     * iter-58 F2 Phase 8.3 overload: same as the 2-arg [rewrite] but, when
     * a fenced code block declares `language-markdown` AND [markdownEngine]
     * is supplied, delegates the block's body to
     * [MarkdownCodeFences.tokenize] so any nested fenced sub-language
     * code blocks inside that markdown body get sub-language scopes
     * (e.g. a `\`\`\`kotlin` fence inside the markdown preview's body
     * is highlighted with the kotlin grammar, not just as markdown text).
     *
     * For every other lang, behavior is identical to the 2-arg call —
     * preserving iter-57's HTML-emission contract byte-for-byte. When
     * [markdownEngine] is null OR [markdownSubEngines] is empty, the
     * delegation path is a no-op fallback to the standard path.
     *
     * Anti-bluff (CONST-035): when [MarkdownCodeFences.tokenize] throws
     * or returns an empty list, we honor the same fallback contract as
     * the 2-arg path — the original block bytes are preserved verbatim.
     */
    suspend fun rewrite(
        html: String,
        highlighter: SyntaxHighlighter,
        markdownEngine: TokenizerEngine?,
        markdownSubEngines: Map<String, TokenizerEngine>,
    ): String {
        val matches = codeBlockRegex.findAll(html).toList()
        if (matches.isEmpty()) return html
        val sb = StringBuilder(html.length + matches.size * 200)
        var cursor = 0
        for (m in matches) {
            sb.append(html, cursor, m.range.first)
            val lang = m.groupValues[1].ifBlank { null }
            val rawHtmlBody = m.groupValues[2]
            val rendered: String = if (lang != null && EnabledFormatGate.isEnabled(lang)) {
                val decoded = unescapeHtml(rawHtmlBody)
                try {
                    val tokens = tokensFor(
                        lang = lang,
                        body = decoded,
                        highlighter = highlighter,
                        markdownEngine = markdownEngine,
                        markdownSubEngines = markdownSubEngines,
                    )
                    if (tokens.isEmpty()) {
                        m.value
                    } else {
                        buildTokenSpans(decoded, tokens, lang)
                    }
                } catch (t: Throwable) {
                    // CONST-035 anti-bluff: graceful — original block preserved.
                    // Caller layers may log; we never substitute fake spans.
                    if (t is kotlinx.coroutines.CancellationException) throw t
                    m.value
                }
            } else {
                m.value
            }
            sb.append(rendered)
            cursor = m.range.last + 1
        }
        sb.append(html, cursor, html.length)
        return sb.toString()
    }

    /**
     * Resolve tokens for a fenced-block body. When the block's [lang] is
     * `markdown` AND a [markdownEngine] is supplied, the body itself may
     * contain further fenced sub-language blocks — delegate to
     * [MarkdownCodeFences.tokenize] so those nested fences pick up their
     * sub-grammar scopes. Otherwise (non-markdown lang OR markdownEngine
     * not supplied), fall through to the existing [SyntaxHighlighter]
     * tokenize path which is the iter-57 behavior.
     */
    private suspend fun tokensFor(
        lang: String,
        body: String,
        highlighter: SyntaxHighlighter,
        markdownEngine: TokenizerEngine?,
        markdownSubEngines: Map<String, TokenizerEngine>,
    ): List<Token> {
        if (lang == "markdown" && markdownEngine != null && markdownSubEngines.isNotEmpty()) {
            return MarkdownCodeFences.tokenize(
                text = body,
                markdownEngine = markdownEngine,
                subEnginesByLang = markdownSubEngines,
            )
        }
        return highlighter.tokens(body, lang)
    }

    /**
     * Build a `<pre><code class="language-X"><span class="tok-…">…</span>…</code></pre>`
     * string from the raw [text] body, [tokens] produced for it by the
     * tokenizer engine, and the originating [lang]. Tokens are emitted
     * in sorted byte-offset order; overlapping tokens (where a later
     * token starts before the previous one ended) are dropped to avoid
     * malformed HTML.
     */
    private fun buildTokenSpans(text: String, tokens: List<Token>, lang: String): String {
        val out = StringBuilder()
        out.append("<pre><code class=\"language-").append(lang).append("\">")
        var pos = 0
        for (tok in tokens.sortedBy { it.startByte }) {
            if (tok.startByte < pos) continue
            val s = tok.startByte.coerceIn(0, text.length)
            val e = tok.endByte.coerceIn(s, text.length)
            if (s > pos) {
                out.append(escapeHtml(text.substring(pos, s)))
            }
            if (e > s) {
                val vsScope = ScopeMapper.treeSitterToVsCode(tok.scope)
                val cssClass = "tok-" + vsScope.replace('.', '-')
                out.append("<span class=\"").append(cssClass).append("\">")
                out.append(escapeHtml(text.substring(s, e)))
                out.append("</span>")
            }
            pos = e
        }
        if (pos < text.length) {
            out.append(escapeHtml(text.substring(pos)))
        }
        out.append("</code></pre>")
        return out.toString()
    }

    /**
     * Minimal HTML-text escape for the four characters relevant inside
     * `<pre><code>…</code></pre>`. Single/double quotes need not be
     * escaped because they cannot terminate any attribute we emit here.
     */
    private fun escapeHtml(s: String): String =
        s.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")

    /**
     * Inverse of [escapeHtml] — undo the HTML escaping that the format
     * parser applied to the fenced-block body before we tokenize it.
     * `&amp;` must be last so that already-decoded `&lt;` text is not
     * double-decoded. Numeric entities (`&#xx;`, `&#xNN;`) are not
     * generated by the Yole format parsers so we don't decode them.
     */
    private fun unescapeHtml(s: String): String =
        s.replace("&lt;", "<")
            .replace("&gt;", ">")
            .replace("&quot;", "\"")
            .replace("&#39;", "'")
            .replace("&amp;", "&")
}
